---
- name: install
  apt: name={{ item }} state=present
  with_items:
    - mariadb-server
    - mariadb-client
    - python-mysqldb

- name: change default user to root/root
  mysql_user: name=root password=root host=localhost

- name: copy .my.cnf file for root
  copy:
    src=user-my.cnf
    dest=/root/.my.cnf
    owner=root
    mode=0600

- name: copy .my.cnf for vagrant
  copy:
    src=user-my.cnf
    dest=/home/vagrant/.my.cnf
    owner=vagrant
    mode=0600

- name: MySQL | Copy mysql config
  copy:
    src=my.cnf
    dest=/etc/mysql/my.cnf
  notify:
    restart mysql