---
- name: install
  apt: name={{ item }} state=present
  with_items:
    - memcached

- name: configure memcached.conf
  template:
    src=memcached.conf.j2
    dest=/etc/memcached.conf
  notify:
      - restart memcached
