---
- name: add key
  apt_key: keyserver=keyserver.ubuntu.com id=0x5a16e7281be7a449 state=present

- name: app repository
  apt_repository: repo='deb http://dl.hhvm.com/ubuntu trusty main' state=present

- name: install
  apt: name={{ item }} state=present
  with_items:
    - hhvm
  notify:
    - restart hhvm
    
- name: link hhvm rc0.d
  file:
    src=/etc/init.d/hhvm
    dest=/etc/rc0.d/K01hhvm
    state=link

- name: link hhvm rc1.d
  file:
    src=/etc/init.d/hhvm
    dest=/etc/rc1.d/K01hhvm
    state=link

- name: link hhvm rc2.d
  file:
    src=/etc/init.d/hhvm
    dest=/etc/rc2.d/S01hhvm
    state=link

- name: link hhvm rc3.d
  file:
    src=/etc/init.d/hhvm
    dest=/etc/rc3.d/S01hhvm
    state=link

- name: link hhvm rc4.d
  file:
    src=/etc/init.d/hhvm
    dest=/etc/rc4.d/S01hhvm
    state=link

- name: link hhvm rc5.d
  file:
    src=/etc/init.d/hhvm
    dest=/etc/rc5.d/S01hhvm
    state=link

- name: link hhvm rc6.d
  file:
    src=/etc/init.d/hhvm
    dest=/etc/rc6.d/K01hhvm
    state=link    

- name: fix user in init script
  lineinfile:
    dest=/etc/init.d/hhvm
    line='RUN_AS_USER="vagrant"'
    regexp='^RUN_AS_USER\='
    state=present

- name: fix group in init script
  lineinfile:
    dest=/etc/init.d/hhvm
    line='RUN_AS_GROUP="vagrant"'
    regexp='^RUN_AS_GROUP\='
    state=present

- name: configure php.ini
  template:
    src=php.ini.j2
    dest=/etc/hhvm/php.ini
  notify:
    - restart hhvm

- name: configure server.ini
  template:
    src=server.ini.j2
    dest=/etc/hhvm/server.ini
  notify:
    - restart hhvm