#! /bin/sh
### BEGIN INIT INFO
# Provides:          php7-fpm
# Required-Start:    $all
# Required-Stop:     $all
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts php-7.0.0-fpm
# Description:       starts the PHP FastCGI Process Manager daemon
### END INIT INFO
php_fpm_BIN=/usr/local/php7/sbin/php-fpm
php_fpm_CONF=/usr/local/php7/etc/php-fpm.conf
php_fpm_PID=/usr/local/php7/var/run/php-fpm.pid
php_opts="--daemonize --fpm-config $php_fpm_CONF"

case "$1" in
        start)
                start-stop-daemon --start --quiet --pidfile $php_fpm_PID --exec $php_fpm_BIN --test > /dev/null \
                        || return 1
                start-stop-daemon --start --quiet --pidfile $php_fpm_PID --exec $php_fpm_BIN -- $php_opts 2>/dev/null \
                        || return 2
        ;;
        stop)
                start-stop-daemon --stop --quiet --retry=QUIT/$TIMEOUT/TERM/5/KILL/5 --pidfile $php_fpm_PID --name php7-fpm
                RETVAL="$?"
                [ "$RETVAL" = 2 ] && return 2
                start-stop-daemon --stop --quiet --oknodo --retry=0/30/TERM/5/KILL/5 --exec $php_fpm_BIN
                [ "$?" = 2 ] && return 2
                # Many daemons don't delete their pidfiles when they exit.
                rm -f $php_fpm_PID
                return "$RETVAL"
        ;;
        restart)
                $0 stop
                $0 start
        ;;
        reload)
                start-stop-daemon --stop --signal USR2 --quiet --pidfile $php_fpm_PID --name php7-fpm
                return 0
        ;;
        *)
                echo "Usage: $0 {start|stop|force-quit|restart|reload}"
                exit 1
        ;;
esac