---
- name: add key
  apt_key: keyserver=keyserver.ubuntu.com id=7F0CEB10 state=present

- name: app repository
  apt_repository: repo='deb http://repo.mongodb.org/apt/debian wheezy/mongodb-org/3.0 main' state=present

- name: install
  apt: name={{ item }} state=present
  with_items:
    - mongodb-org

- name: configure mongod.conf
  template:
    src=mongod.conf.j2
    dest=/etc/mongod.conf
  notify:
      - restart mongodb

- name: copy user script
  template:
    src=createuser.js.j2
    dest=~/createuser.js

- name: add admin user
  command: mongo --shell ~/createuser.js

- name: copy .mongorc.js file for root
  template:
    src=user-mongorc.js.j2
    dest=/root/.mongorc.js
    owner=root
    mode=0600

- name: copy .mongorc.js for vagrant
  template:
    src=user-mongorc.js.j2
    dest=/home/vagrant/.mongorc.js
    owner=vagrant
    mode=0600