---
- name: APT | Update apt cache
  apt: update_cache=yes

- name: APT | Install requirements
  apt: name={{ item }} state=present
  with_items:
    - aptitude

- name: APT | Upgrade
  apt: upgrade=full