---
- name: Locale | Install locales
  apt: name={{ item }} state=present
  with_items:
    - locales-all

- name: Locale | Generate {{ locale }}
  command: /usr/sbin/locale-gen {{ locale }}

- name: Locale | Set locale to {{ locale }}
  command: /usr/sbin/update-locale LANG={{ locale }} LC_ALL={{ locale }}