---
- name: apt | upgrade
  apt: update_cache=yes upgrade=full

- name: apt | install packages
  apt: name={{ item }} state=present
  with_items: general.packages

- name: locale | install
  apt: name={{ item }} state=present
  with_items:
    - locales-all

- name: locale | Generate de_CH.UTF-8
  command: /usr/sbin/locale-gen de_CH.UTF-8

- name: locale | Set locale to de_CH.UTF-8
  command: /usr/sbin/update-locale LANG=de_CH.UTF-8 LC_ALL=de_CH.UTF-8

- name: timezone | Set /etc/localtime to Europe/Zurich
  command: /bin/cp /usr/share/zoneinfo/Europe/Zurich /etc/localtime

- name: timezone | Update tzdata
  command: dpkg-reconfigure --frontend noninteractive tzdata

- name: bash | copy .bash_vagrant
  template:
    src=bash_vagrant.j2
    dest=/home/vagrant/.bash_vagrant

- name: bash | register .bash_vagrant
  lineinfile: dest=/home/vagrant/.bashrc line='. ~/.bash_vagrant'
