---
- hosts: all
  sudo: true
  roles:
    - general
    - { role: elasticsearch, when: role.elasticsearch }
    - { role: freetds, when: role.freetds }
    - git
    - { role: hhvm, when: phpversion == 'hhvm' }
    - { role: java, when: role.java }
    - { role: mariadb, when: role.mariadb }
    - { role: memcached, when: role.memcached }
    - { role: mongodb, when: role.mongodb }
    - nginx
    - { role: nodejs, when: role.nodejs }
    - { role: php56, when: phpversion == 5.6 }
    - { role: php70, when: phpversion == 7.0 }
    - php-commandlinetools
    - { role: postgresql, when: role.postgresql }
    - { role: redis, when: role.redis }
    - { role: ruby, when: role.ruby }
    - cleanup
